### ISSUE TITLE
Feature request: Support remote connections

### ISSUE THREAD

**Issue by baarkerlounger** [ppvan/psequel#40]
It would be useful to be able to connect to remote databases over SSH Tunnel.

**Comment by ppvan** [comment]
I'll working on it on the next release.

**Comment by ppvan** [comment]
After some investigations, I don't think this feature is useful. User can create a SSH tunnel by themselves then connect with psequel as normal if tunneled port.

Implement this feature is a bit complicated and required permission to read user's $HOME
