### ISSUE TITLE
Unable to list tables from docker container 

### ISSUE THREAD

**Issue by gift-sequoiaat** [ppvan/psequel#43]
I can list my schemas, but I can't list my tables or run any queries while using posgres using docker. Is there something I'm missing?

This is my system info : 

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

Docker Image Info:  postgres:latest 
version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:

![image](https://github.com/ppvan/psequel/assets/120704344/93c1faf3-5c06-41b5-9519-f52c8b7bd428)

**Comment by ppvan** [comment]
i'm not sure, maybe need more infomation.
I mostly test the app with local connection, may need more time to make it work with docker or ssh tunel..

**Comment by gift-sequoiaat** [comment]
> i'm not sure, maybe need more infomation. I mostly test the app with local connection, may need more time to make it work with docker or ssh tunel..

sure thanks, loved the ui and design.

**Comment by ppvan** [comment]
@gift-sequoiaat I can't find why it doesn't works, the bug seem related to flatpak builder.
You can try to install new version under [Release](https://github.com/ppvan/psequel/releases/tag/v0.1.6).

**Comment by gift-sequoiaat** [comment]
Sure thanks @ppvan  will update you on it

**Comment by ppvan** [comment]
@gift-sequoiaat I just test it and connection from docker should works fine, the bug seem to be only happen with flathub
The version in the release should be fine, i suppose.

**Comment by gift-sequoiaat** [comment]
Hello, @ppvan.  Sorry for the delayed response. I am unable to build it using gnome builder, possibly because I have stopped the Postgresql service on my local machine. I will spawn a VM and validate it.
