### ISSUE TITLE
No SSL support in Flatpak version

### ISSUE THREAD

**Issue by danastasio** [ppvan/psequel#44]
Hello,

This app looks great and I'm excited to try it out, but when I try and use an SSL connection in the Flatpak version I get the following error: 

> sslmode value "require" invalid when SSL support is not compiled in

Would compiling from source resolve this? Am I missing a flatpak dependency?

Using version 0.1.3

**Comment by ppvan** [comment]
Yeah no, that's my bad.
SSL is not work yet, i haven't used SSH before so...
Yes, if you can compile with meson, ssh will work because it will use your installation postgres

Anyway i'm will try to support SSL ASAP. I will inform you then
