### ISSUE TITLE
Use of PostgreSQL logo and trademarks

### ISSUE THREAD

**Issue by tdworz** [ppvan/psequel#49]
Do you have permission to use the PostgreSQL logo as part of your logo? If no, please stop using the PostgreSQL logo. https://www.postgresql.org/about/policies/trademarks/

I would also suggest you contact Postgres to see if they consider the name _psequel_ an infringement on their trademark. It certainly implies an affiliation in my mind. board@lists.postgres.ca

**Comment by ppvan** [comment]
Yeah, i'm not good at this tracemark
I'll remove it from the logo
About application name i really want to keep it because this tend to be a successor of [psequel](https://psequel.com/) which is discontinued since 2018

Thanks for the advice, I'm just a college student making a toy app so I'm do not know about this stuff

**Comment by baarkerlounger** [comment]
Changing the name to something more generic might also be beneficial if you do later decide to add support for other databases.

**Comment by ppvan** [comment]
Maybe, but i can't come up with any good names. But maybe a good idea to avoid all of this stuff

**Comment by tdworz** [comment]
If you keep the name, maybe you can put a note in the description like: `This project is not a part of or affiliated with PostgreSQL.` That way people will understand it's a community project and not official.

A lot of the concern with this stuff is to not give an incorrect impression. For example, when I came across your project on Flathub today I thought, "wow Postgres came out with a new GUI tool!" If you didn't have the elephant logo on it and said you're not part of Postgres, I would instead have thought, "wow someone in the community came out with a new database GUI tool!" And that's exactly the end result you want to achieve.

**Comment by ppvan** [comment]
Thank you very much !!, i will update the README and flathub accordingly

**Comment by ppvan** [comment]
updated in commits 6fa469880e5b452b6e9dfd9c91f70fc81e1cd8a8 and 3b8a4bc20be8a38b62a8d90fb0b4aab5e56cd77b

The logo in flathub still doesn't change, because of cache or something, hopefully they'll updated soon
