### ISSUE TITLE
preferences panel, and some functionality issues

### ISSUE THREAD

**Issue by golamrabbiazad** [ppvan/psequel#56]
- In the preferences, font family, color scheme, and all options hang on functioning. So, If I change something and then close the preference panel, it hangs on.
- After table creation, the created table does not show on the left side, on reload, or on logout. Tables only show when on the quit psequel app and then run.

If any additional information or logs are needed to diagnose the problem, please let me know and I'll be happy to provide them.

**Comment by ppvan** [comment]
@golamrabbiazad
Thank for bug report ! 
After I test the current flatpak, there are bugs as you witness.
I just fix the schema reload yesterday, so it should be fine after i update it.
About the editor font make the app hangs, I 'll need more investigation, but it indeed happens
