### ISSUE TITLE
Flatpak Version SSL Broken

### ISSUE THREAD

**Issue by Wingar** [ppvan/psequel#83]
Error message when trying to connect with SSL toggled on.
`invalid sslmode value: "required"` 

Downloaded from Flathub, 0.2.0

**Comment by ppvan** [comment]
That's weird, it's should be `require`. Let me check the source code realquick

**Comment by ppvan** [comment]
May be you're on old version. I just republish latest one on flathub
If flathub not update yet, try this command to get the test build

```
flatpak install https://dl.flathub.org/build-repo/112932/me.ppvan.psequel.flatpakref
```

**Comment by Wingar** [comment]
That resolved it! Thanks for the fix!
